//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Description { get; set; }
        public string DeparturePoint { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
